"""add api request fields

Revision ID: af8bcd3faa4b
Revises: c82e88547471
Create Date: 2026-02-14 00:29:07.685019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8bcd3faa4b'
down_revision: Union[str, Sequence[str], None] = 'c82e88547471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exile_api_environments',
    sa.Column('name', sa.String(length=128), nullable=False, comment='环境名称'),
    sa.Column('variables', sa.JSON(), nullable=False, comment='环境变量字典'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否默认环境'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间(结构化时间)'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间(时间戳)'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间(结构化时间)'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=True, comment='更新时间(时间戳)'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='0正常;其他:已删除'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exile_api_request_datasets',
    sa.Column('request_id', sa.BigInteger(), nullable=False, comment='测试用例ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='数据集名称'),
    sa.Column('creator', sa.String(length=32), nullable=True, comment='创建人'),
    sa.Column('creator_id', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('modifier', sa.String(length=32), nullable=True, comment='更新人'),
    sa.Column('modifier_id', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('variables', sa.JSON(), nullable=False, comment='变量字典(可用于模板替换, 如 user_id/token)'),
    sa.Column('query_params', sa.JSON(), nullable=False, comment='Query参数'),
    sa.Column('headers', sa.JSON(), nullable=False, comment='请求头'),
    sa.Column('cookies', sa.JSON(), nullable=False, comment='Cookies'),
    sa.Column('body_type', sa.String(length=32), nullable=True, comment='请求体类型覆盖'),
    sa.Column('body_data', sa.JSON(), nullable=False, comment='结构化请求体'),
    sa.Column('body_raw', sa.Text(), nullable=True, comment='原始请求体'),
    sa.Column('expected', sa.JSON(), nullable=False, comment='预期结果配置'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否默认数据集'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序值'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间(结构化时间)'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间(时间戳)'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间(结构化时间)'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=True, comment='更新时间(时间戳)'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='0正常;其他:已删除'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exile_api_request_runs',
    sa.Column('request_id', sa.BigInteger(), nullable=False, comment='测试用例ID'),
    sa.Column('scenario_id', sa.BigInteger(), nullable=True, comment='场景ID(场景执行时记录)'),
    sa.Column('scenario_case_id', sa.BigInteger(), nullable=True, comment='场景步骤ID'),
    sa.Column('dataset_id', sa.BigInteger(), nullable=True, comment='数据集ID'),
    sa.Column('dataset_snapshot', sa.JSON(), nullable=False, comment='执行时数据集快照'),
    sa.Column('request_snapshot', sa.JSON(), nullable=False, comment='执行时请求快照'),
    sa.Column('response_status_code', sa.Integer(), nullable=True, comment='响应状态码'),
    sa.Column('response_headers', sa.JSON(), nullable=False, comment='响应头'),
    sa.Column('response_body', sa.Text(), nullable=True, comment='响应体'),
    sa.Column('response_time_ms', sa.Integer(), nullable=True, comment='响应耗时(毫秒)'),
    sa.Column('is_success', sa.Boolean(), nullable=False, comment='执行是否成功'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='执行错误信息'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间(结构化时间)'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间(时间戳)'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间(结构化时间)'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=True, comment='更新时间(时间戳)'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='0正常;其他:已删除'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exile_api_requests',
    sa.Column('env_id', sa.BigInteger(), nullable=True, comment='默认环境ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='测试用例名称'),
    sa.Column('method', sa.String(length=16), nullable=False, comment='HTTP方法'),
    sa.Column('url', sa.String(length=2048), nullable=False, comment='请求URL'),
    sa.Column('creator', sa.String(length=32), nullable=True, comment='创建人'),
    sa.Column('creator_id', sa.BigInteger(), nullable=True, comment='创建人ID'),
    sa.Column('modifier', sa.String(length=32), nullable=True, comment='更新人'),
    sa.Column('modifier_id', sa.BigInteger(), nullable=True, comment='更新人ID'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('base_query_params', sa.JSON(), nullable=False, comment='基础Query参数'),
    sa.Column('base_headers', sa.JSON(), nullable=False, comment='基础请求头'),
    sa.Column('base_cookies', sa.JSON(), nullable=False, comment='基础Cookies'),
    sa.Column('body_type', sa.String(length=32), nullable=False, comment='请求体类型:none/json/form-urlencoded/form-data/raw/binary'),
    sa.Column('base_body_data', sa.JSON(), nullable=False, comment='基础结构化请求体'),
    sa.Column('base_body_raw', sa.Text(), nullable=True, comment='基础原始请求体'),
    sa.Column('timeout_ms', sa.Integer(), nullable=False, comment='超时时间(毫秒)'),
    sa.Column('follow_redirects', sa.Boolean(), nullable=False, comment='是否跟随重定向'),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False, comment='是否校验SSL证书'),
    sa.Column('proxy_url', sa.String(length=1024), nullable=True, comment='代理地址'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序值'),
    sa.Column('execute_count', sa.Integer(), nullable=False, comment='执行次数'),
    sa.Column('case_status', sa.String(length=16), nullable=False, comment='用例状态:已完成/开发中/调试中/弃用'),
    sa.Column('is_copied_case', sa.Boolean(), nullable=False, comment='是否复制生成'),
    sa.Column('is_public_visible', sa.Boolean(), nullable=False, comment='是否公共可见'),
    sa.Column('creator_only_execute', sa.Boolean(), nullable=False, comment='是否仅创建者执行'),
    sa.Column('data_driven_enabled', sa.Boolean(), nullable=False, comment='是否开启数据驱动'),
    sa.Column('dataset_run_mode', sa.String(length=16), nullable=False, comment='数据集执行模式:single/all'),
    sa.Column('default_dataset_id', sa.BigInteger(), nullable=True, comment='默认数据集ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间(结构化时间)'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间(时间戳)'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间(结构化时间)'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=True, comment='更新时间(时间戳)'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='0正常;其他:已删除'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exile_test_scenario_cases',
    sa.Column('scenario_id', sa.BigInteger(), nullable=False, comment='场景ID'),
    sa.Column('request_id', sa.BigInteger(), nullable=False, comment='测试用例ID'),
    sa.Column('step_no', sa.Integer(), nullable=False, comment='执行顺序'),
    sa.Column('dataset_id', sa.BigInteger(), nullable=True, comment='固定执行数据集ID'),
    sa.Column('dataset_run_mode', sa.String(length=16), nullable=False, comment='场景步骤数据集模式:request_default/single/all'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('stop_on_fail', sa.Boolean(), nullable=False, comment='步骤失败是否中断'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间(结构化时间)'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间(时间戳)'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间(结构化时间)'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=True, comment='更新时间(时间戳)'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='0正常;其他:已删除'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exile_test_scenarios',
    sa.Column('env_id', sa.BigInteger(), nullable=True, comment='默认环境ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='场景名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='场景说明'),
    sa.Column('run_mode', sa.String(length=16), nullable=False, comment='执行模式:sequence/parallel'),
    sa.Column('stop_on_fail', sa.Boolean(), nullable=False, comment='失败是否中断'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序值'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间(结构化时间)'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间(时间戳)'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间(结构化时间)'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=True, comment='更新时间(时间戳)'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='0正常;其他:已删除'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exile_test_scenarios')
    op.drop_table('exile_test_scenario_cases')
    op.drop_table('exile_api_requests')
    op.drop_table('exile_api_request_runs')
    op.drop_table('exile_api_request_datasets')
    op.drop_table('exile_api_environments')
    # ### end Alembic commands ###
