"""init schema

Revision ID: c82e88547471
Revises: 
Create Date: 2026-02-13 22:45:51.673087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82e88547471'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exile_admin',
    sa.Column('username', sa.String(length=255), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('nickname', sa.String(length=128), nullable=True, comment='昵称'),
    sa.Column('phone', sa.String(length=64), nullable=True, comment='手机号'),
    sa.Column('mail', sa.String(length=256), nullable=True, comment='邮箱'),
    sa.Column('code', sa.String(length=64), nullable=True, comment='用户编号'),
    sa.Column('seat', sa.String(length=64), nullable=True, comment='座位编号'),
    sa.Column('department', sa.String(length=64), nullable=True, comment='部门'),
    sa.Column('position', sa.String(length=64), nullable=True, comment='职位'),
    sa.Column('superior', sa.String(length=64), nullable=True, comment='上级'),
    sa.Column('login_type', sa.String(length=64), nullable=True, comment='登录类型:single;many'),
    sa.Column('is_tourist', sa.Integer(), nullable=False, comment='0-游客账户;1-非游客账户'),
    sa.Column('creator', sa.String(length=32), nullable=True, comment='创建人'),
    sa.Column('creator_id', sa.BigInteger(), nullable=True, comment='创建人id'),
    sa.Column('modifier', sa.String(length=32), nullable=True, comment='更新人'),
    sa.Column('modifier_id', sa.BigInteger(), nullable=True, comment='更新人id'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间(结构化时间)'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间(时间戳)'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间(结构化时间)'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=True, comment='更新时间(时间戳)'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='0正常;其他:已删除'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exile_aps_tasks',
    sa.Column('task_id', sa.String(length=64), nullable=False, comment='任务id'),
    sa.Column('trigger_type', sa.String(length=16), nullable=False, comment='触发器类型:date;interval;cron'),
    sa.Column('trigger_param', sa.JSON(), nullable=False, comment='触发器参数'),
    sa.Column('task_function_name', sa.String(length=255), nullable=True, comment='任务函数名称'),
    sa.Column('task_function_args', sa.JSON(), nullable=False, comment='任务参数:args'),
    sa.Column('task_function_kwargs', sa.JSON(), nullable=False, comment='任务参数:kwargs'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间(结构化时间)'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间(时间戳)'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间(结构化时间)'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=True, comment='更新时间(时间戳)'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='0正常;其他:已删除'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exile_aps_tasks')
    op.drop_table('exile_admin')
    # ### end Alembic commands ###
